apps/productos/urls.py
from django.conf.urls import url
from apps.productos.views import index, productos_view, productos_edit, productos_delete, productos_precio, productos_precio_nuevo, productos_precio_edit, productos_precio_delete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    url(r'^nuevo$', login_required(productos_view), name='productos_crear'),
    url(r'^editar/(?P<id_producto>\d+)/$', login_required(productos_edit), name='productos_editar'),
    url(r'^eliminar/(?P<id_producto>\d+)/$', login_required(productos_delete), name='productos_eliminar'),
    url(r'^precio/(?P<id_producto>\d+)/$', login_required(productos_precio), name='productos_precio'),
    url(r'^precio/nuevo/(?P<id_producto>\d+)/$', login_required(productos_precio_nuevo), name='productos_precio_nuevo'),
    url(r'^precio/editar/(?P<id_producto>\d+)/(?P<id_precio>\d+)/$', login_required(productos_precio_edit), name='productos_precio_editar'),
    url(r'^precio/eliminar/(?P<id_producto>\d+)/(?P<id_precio>\d+)/$', login_required(productos_precio_delete), name='productos_precio_eliminar')
]

lista123/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.solicitudes.views import index_principal
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', index_principal, name='inicio'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,{'template_name':'base/login.html'} ,name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/grados/', include('apps.grados.urls', namespace="grados")),
    url(r'^dashboard/institutos/', include('apps.institutos.urls', namespace="institutos")),
    url(r'^dashboard/listas/', include('apps.listas.urls', namespace="listas")),
    url(r'^dashboard/productos/', include('apps.productos.urls', namespace="productos")),
    url(r'^dashboard/solicitudes/', include('apps.solicitudes.urls', namespace="solicitudes")),
    url(r'^dashboard/sugerencias/', include('apps.sugerencias.urls', namespace="sugerencias")),
    url(r'^dashboard/utilidades/', include('apps.utilidades.urls', namespace="utilidades")),
] #+ static(settings.STATIC_ROOT, document_root = settings.STATIC_ROOT)

apps/productos/models.py
from django.db import models
from apps.utilidades.models import Categoria

# Create your models here.
class Producto(models.Model):
    nombre = models.TextField()
    fecha_registro = models.DateField()
    garantia = models.BooleanField()
    codigo = models.CharField(max_length=50)
    precio = models.ManyToManyField(Categoria, through= 'ListaPrecio', through_fields= ('producto', 'categoria'))

    def __str__(self):
        return '{}'.format(self.nombre)

class ListaPrecio(models.Model):
    producto = models.ForeignKey(Producto, null=False, blank=False)
    categoria = models.ForeignKey(Categoria, null=False, blank=False)
    precio = models.DecimalField(max_digits=20, decimal_places=2)

apps/productos/forms.py
from django import forms
from apps.productos.models import Producto, ListaPrecio


class ProductosForm(forms.ModelForm):

    class Meta:
        model = Producto

        fields =[
            'nombre',
            'fecha_registro',
            'garantia',
            'codigo',
        ]

        labels = {
            'nombre':'Nombre',
            'fecha_registro' :'Fecha',
            'garantia' :'Garantia',
            'codigo':'Codigo',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Nombre'}),
            'fecha_registro': forms.DateInput(attrs={'id': 'datepicker','class':'form-control border-input', 'type': 'text', 'placeholder': 'dd/MM/YYYY'}),
            'garantia': forms.CheckboxInput(attrs={'class':'form-control border-input',}),
            'codigo': forms.NumberInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Código'}),
        }

class PreciosForm(forms.ModelForm):

    class Meta:
        model = ListaPrecio

        fields = [
            'producto',
            'categoria',
            'precio',
        ]

        labels = {
            'producto': 'Producto',
            'categoria': 'Categoria',
            'precio': 'Precio',
        }

        widgets = {
            'producto' :forms.HiddenInput(attrs={'class':'form-control border-input', 'id' : 'producto'}),
            'categoria' : forms.Select(attrs={'class':'form-control border-input'}),
            'precio': forms.NumberInput(attrs={'class':'form-control border-input'}),
        }

apps/productos/views.py
from django.shortcuts import render, redirect
from apps.productos.forms import ProductosForm, PreciosForm
from apps.productos.models import Producto, ListaPrecio, Categoria

# Create your views here.
def index(request):
    producto = Producto.objects.all().order_by('id')
    contexto = {'productos':producto}
    return render(request,'productos/listar.html', contexto)

def productos_view(request):
    if request.method == 'POST':
        form = ProductosForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('productos:index')
    else:
        form = ProductosForm()
    return render(request, 'productos/agregar.html', {'form': form})

def productos_edit (request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    if request.method == 'GET':
        form = ProductosForm(instance=producto)
    else:
        form = ProductosForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
        return redirect('productos:index')
    return render(request, 'productos/editar.html', {'form':form})

def productos_delete (request, id_producto):
    producto = Producto.objects.get(id = id_producto)
    if request.method == 'POST':
        producto.delete()
        return redirect('productos:index')
    return render(request, 'productos/eliminar.html', {'producto':producto})

def productos_precio(request, id_producto):
    #producto = Producto.objects.filter(precio__producto= id_producto)
    producto = ListaPrecio.objects.select_related("categoria").filter(producto=id_producto)
    contexto = {'productos':producto, 'id_producto' : id_producto}
    return render(request,'productos/listaprecios.html', contexto)

def productos_precio_nuevo(request, id_producto):
    if request.method == 'POST':
        form = PreciosForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('productos:productos_precio', id_producto = id_producto)
    else:
        form = PreciosForm
    return render(request, 'productos/agregarprecio.html', {'form': form, 'producto':id_producto })

def productos_precio_edit (request, id_producto, id_precio):
    precio = ListaPrecio.objects.get(id=id_precio)
    if request.method == 'GET':
        form = PreciosForm(instance=precio)
    else:
        form = PreciosForm(request.POST, instance=precio)
        if form.is_valid():
            form.save()
        return redirect('productos:productos_precio', id_producto=id_producto)
    return render(request, 'productos/editarprecio.html', {'form':form, 'producto':id_producto})

def productos_precio_delete (request, id_producto, id_precio):
    precio = ListaPrecio.objects.get(id=id_precio)
    if request.method == 'POST':
        precio.delete()
        return redirect('productos:productos_precio', id_producto=id_producto)
    return render(request, 'productos/eliminarprecio.html', {'precio':precio, 'producto': id_producto})

templates/productos/agregar.html
{% extends 'productos/listar.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script>
        $.datepicker.regional['es'] = {
        closeText: 'Cerrar',
        prevText: '< Ant',
        nextText: 'Sig >',
        currentText: 'Hoy',
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
        dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
        weekHeader: 'Sm',
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: ''
        };
        $.datepicker.setDefaults($.datepicker.regional['es']);
        $(function () {
            $("#datepicker").datepicker();
        });
</script>

{% endblock %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">{% block titleform %}Nuevo Producto {% endblock %}</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Nombre</label>
                                {{ form.nombre }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Fecha Registro</label>
                                {{ form.fecha_registro }}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Garantía</label>
                                {{ form.garantia }}
                            </div>
                        </div>
                         <div class="col-md-5">
                            <div class="form-group">
                                <label>Código</label>
                                {{ form.codigo }}
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Guardar</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/productos/agregarprecio.html
{% extends 'productos/listar.html' %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">{% block titleform %}Nuevo Precio {% endblock %}</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    {{ form.producto }}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Categoría</label>
                                {{ form.categoria}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Precio</label>
                                {{ form.precio }}
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Guardar</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
    <script>
        document.getElementById("producto").value = {{ producto }}
    </script>
{% endblock %}

templates/productos/editar.html
{% extends 'productos/agregar.html' %}

{% block titleform %}
    Editar Producto
{% endblock %}

templates/productos/editarprecio.html
{% extends 'productos/agregarprecio.html' %}

{% block titleform %}
    Editar Precio
{% endblock %}

templates/productos/eliminar.html
{% extends 'productos/listar.html' %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">¿Desea eliminar el registro de {{ producto.nombre }}?</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Si, Eliminar</button>
                        <a class="btn btn-info btn-fill btn-wd " href="{% url 'productos:index' %}">Cancelar</a>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/productos/eliminarprecio.html
{% extends 'productos/listaprecios.html' %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">¿Desea eliminar el registro de {{ precio.producto.nombre }} para la categoría {{ precio.categoria }}?</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Si, Eliminar</button>
                        <a class="btn btn-info btn-fill btn-wd " href="{% url 'productos:productos_precio' producto %}">Cancelar</a>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/productos/listaprecios.html
{% extends 'base/base.html' %}

{% block title %}
    Productos
{% endblock %}

{% block producto %}
    class = "active"
{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Listado</h4>
            <p class="category">Lista de Precios Almacenados</p>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">
                <thead>
                <th>ID</th>
                <th>Categoría</th>
                <th>Precio</th>
                <th >Acciones <a href="{% url 'productos:productos_precio_nuevo' id_producto %}" style=" font-size: 18px;" title="Nuevo" class="ti-plus" id ="icon"></a></th>
                </thead>
                <tbody>
                {% if productos %}
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.id }}</td>
                    <td>{{ producto.categoria}}</td>
                    <td>{{ producto.precio }}</td>
                    <td>
                        <a href="{% url 'productos:productos_precio_editar' id_producto producto.id %}" style=" font-size: 22px; margin-left: 3%" title="Editar" class="ti-pencil" id ="icon"></a>
                        <a href="{% url 'productos:productos_precio_eliminar' id_producto producto.id %}" style=" font-size: 22px; margin-left: 5%" title="Eliminar" class="ti-trash" id ="icon"></a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                    <tr>
						<td colspan='5' align='center'>La consulta no devolvió registros</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/productos/listar.html
{% extends 'base/base.html' %}

{% block title %}
    Productos
{% endblock %}

{% block producto %}
    class = "active"
{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Listado</h4>
            <p class="category">Productos Almacenados</p>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">
                <thead>
                <th>ID</th>
                <th>Nombre</th>
                <th>Código</th>
                <th>Fecha de Registro</th>
                <th >Acciones <a href="{% url 'productos:productos_crear' %}" style=" font-size: 18px;" title="Nuevo" class="ti-plus" id ="icon"></a></th>
                </thead>
                <tbody>
                {% if productos %}
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.id }}</td>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.codigo }}</td>
                    <td>{{ producto.fecha_registro}}</td>
                    <td>
                        <a href="{% url 'productos:productos_editar' producto.id %}" style=" font-size: 22px; margin-left: 2%" title="Editar" class="ti-pencil" id ="icon"></a>
                        <a href="{% url 'productos:productos_eliminar' producto.id %}" style=" font-size: 22px; margin-left: 5%" title="Eliminar" class="ti-trash" id ="icon"></a>
                        <a href="{% url 'productos:productos_precio' producto.id %}" style=" font-size: 22px; margin-left: 5%" title="Precio" class="ti-money" id ="icon"></a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                    <tr>
						<td colspan='5' align='center'>La consulta no devolvió registros</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}