apps/solicitudes/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.solicitudes.views import index, cotizar, solicitudes_delete, despachar

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    url(r'^cotizar/(?P<id_solicitud>\d+)/$', login_required(cotizar), name='cotizacion'),
    url(r'^eliminar/(?P<id_solicitud>\d+)/$', login_required(solicitudes_delete), name='eliminar'),
    url(r'^enviar/(?P<id_solicitud>\d+)/$', login_required(despachar), name='enviar'),
]

lista123/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.solicitudes.views import index_principal
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', index_principal, name='inicio'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,{'template_name':'base/login.html'} ,name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/grados/', include('apps.grados.urls', namespace="grados")),
    url(r'^dashboard/institutos/', include('apps.institutos.urls', namespace="institutos")),
    url(r'^dashboard/listas/', include('apps.listas.urls', namespace="listas")),
    url(r'^dashboard/productos/', include('apps.productos.urls', namespace="productos")),
    url(r'^dashboard/solicitudes/', include('apps.solicitudes.urls', namespace="solicitudes")),
    url(r'^dashboard/sugerencias/', include('apps.sugerencias.urls', namespace="sugerencias")),
    url(r'^dashboard/utilidades/', include('apps.utilidades.urls', namespace="utilidades")),
] #+ static(settings.STATIC_ROOT, document_root = settings.STATIC_ROOT)

apps/solicitudes/models.py
from django.db import models
from apps.institutos.models import Instituto
from apps.grados.models import Grado
from apps.productos.models import Producto

# Create your models here.
class Solicitud(models.Model):
    representante = models.CharField(max_length=60)
    telefono = models.CharField(max_length=10)
    correo = models.EmailField()
    instituto = models.ForeignKey(Instituto, null=False, blank=False, on_delete=models.CASCADE)
    grado = models.ForeignKey(Grado, null=False, blank=False, on_delete=models.CASCADE)
    estudiante = models.CharField(max_length=70)
    direccion = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)

apps/solicitudes/forms.py
from django import forms
from apps.solicitudes.models import Solicitud

class SolicitudForm(forms.ModelForm):

    class Meta:
        model = Solicitud

        fields =[
            'representante',
            'telefono',
            'correo',
            'instituto',
            'grado',
            'estudiante',
            'direccion',
            'estado',
        ]

        labels = {
            'representante': 'Representante',
            'telefono': 'Teléfono',
            'correo': 'Correo',
            'instituto': 'Instituto',
            'grado': 'Grado',
            'estudiante': 'Estudiante',
            'direccion':'Direccion',
            'estado': 'Estado',
        }

        widgets = {
            'representante': forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Representante'}),
            'telefono': forms.NumberInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Teléfono'}),
            'correo': forms.EmailInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Correo'}),
            'instituto': forms.HiddenInput(attrs={'class':'form-control border-input'}),
            'grado': forms.Select(attrs={'class':'form-control border-input'}),
            'estudiante': forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Estudiante'}),
            'direccion': forms.Textarea(attrs={'class': 'form-control border-input', 'type': 'text', 'placeholder': 'Direccion'}),
            'estado': forms.HiddenInput(attrs={'class': 'form-control border-input', 'type': 'text', 'value': 'P'})
        }

apps/solicitudes/views.py
from django.shortcuts import render, redirect, render_to_response
from apps.solicitudes.forms import SolicitudForm
from apps.sugerencias.forms import SugerenciaForm
from apps.grados.models import Grado
from apps.solicitudes.models import Solicitud
from django.core.mail import EmailMessage
from django.template import Context
from django.template.loader import get_template
from django.db import connection
from django.contrib import messages

# Create your views here.
def index_principal(request):
    solicitud_form = SolicitudForm(data=request.POST)
    sugerencia_form = SugerenciaForm(data=request.POST)
    grado = Grado.objects.all()
    if request.method == "POST":
        if "change_sugerencia" in request.POST and sugerencia_form.is_valid():
            sugerencia_form.save()
            messages.add_message(request, messages.SUCCESS, 'ok();')
            return redirect('inicio')
        

        if "change_solicitud" in request.POST and solicitud_form.is_valid():
            data = solicitud_form.cleaned_data
            ctx = {
            }
            message = get_template('mail/Bienvenido.html').render(Context(ctx))
            msg = EmailMessage('Solicitud de Cotizacion', message, 'hola@admin.com', [data['correo']])
            msg.content_subtype = 'html'
            msg.send()
            solicitud_form.save()
            return redirect('inicio')

    else:
        solicitud_form = SolicitudForm()
        sugerencia_form = SugerenciaForm()
    return render(request, 'landing/landing.html', {'form': solicitud_form, 'form1':sugerencia_form, 'grados':grado,})

def index(request):
    solicitud = Solicitud.objects.exclude(estado='E').order_by('id')
    contexto = {'solicitudes':solicitud}
    pagi
    return render(request,'solicitudes/listar.html', contexto)

def cotizar(request, id_solicitud):
    query = "SELECT productos_producto.nombre as NOMBRE, productos_listaprecio.precio\
             FROM productos_producto, productos_listaprecio, listas_lista_producto, listas_lista, institutos_instituto\
             WHERE productos_listaprecio.producto_id = productos_producto.id\
             AND productos_producto.id = listas_lista_producto.producto_id\
             AND listas_lista_producto.lista_id = listas_lista.id\
             AND listas_lista.instituto_id = institutos_instituto.id\
             AND institutos_instituto.categoria_id = productos_listaprecio.categoria_id\
             AND listas_lista.id = (SELECT listas_lista.id FROM listas_lista, solicitudes_solicitud\
             WHERE listas_lista.instituto_id = solicitudes_solicitud.instituto_id\
             AND listas_lista.grado_id = solicitudes_solicitud.grado_id\
             AND solicitudes_solicitud.id = "+ id_solicitud +")"

    with connection.cursor() as cursor:
        cursor.execute(query)
        rows = cursor.fetchall()

        contexto = Solicitud.objects.filter(id = id_solicitud)

        if contexto:
            for p in contexto:
                correo = p.correo
                estudiante = p.estudiante

        total = 0
        for a in rows:
            total = total + a[1]

        ctx = {
            'consulta':rows,
            'estudiante':estudiante,
            'precio':total,
        }
        message = get_template('mail/Cotizacion.html').render(Context(ctx))
        msg = EmailMessage('Solicitud de Cotizacion', message, 'hola@admin.com', [correo])
        msg.content_subtype = 'html'
        msg.send()

        query ="UPDATE solicitudes_solicitud SET estado = 'PR' WHERE id ="+id_solicitud
        cursor.execute(query)

    return redirect('solicitudes:index')

def solicitudes_delete (request, id_solicitud):
    solicitud = Solicitud.objects.get(id = id_solicitud)
    if request.method == 'POST':
        solicitud.delete()
        return redirect('solicitudes:index')
    return render(request, 'solicitudes/eliminar.html', {'solicitud':solicitud})

def despachar (request, id_solicitud):
    solicitud = Solicitud.objects.get(id = id_solicitud)
    if request.method == 'POST':
        query = "UPDATE solicitudes_solicitud SET estado = 'E' WHERE id =" + id_solicitud
        with connection.cursor() as cursor:
            cursor.execute(query)
        return redirect('solicitudes:index')
    return render(request, 'solicitudes/enviar.html', {'solicitud': solicitud})

templates/solicitudes/eliminar.html
{% extends 'solicitudes/listar.html' %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">¿Desea eliminar la solicitud realizada por {{ solicitud.representante }}?</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Si, Eliminar</button>
                        <a class="btn btn-info btn-fill btn-wd " href="{% url 'solicitudes:index' %}">Cancelar</a>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/solicitudes/enviar.html
{% extends 'solicitudes/listar.html' %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">¿Desea despachar la solicitud con los siguientes datos?</h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th align='right'>Solicitante:</th>
                            <td>
                                {{ solicitud.representante }}
                            </td>
                        </tr>
                        <tr>
                            <th align='right'>Telefono:</th>
                            <td>
                                {{ solicitud.telefono }}
                            </td>
                        </tr>
                        <tr>
                            <th align='right'>Correo:</th>
                            <td>
                                {{ solicitud.correo }}
                            </td>
                        </tr>
                        <tr>
                            <th align='right'>Direccion:</th>
                            <td>
                                {{ solicitud.direccion }}
                            </td>
                        </tr>
                    </tbody>
                </table>
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Si, Despachar</button>
                        <a class="btn btn-info btn-fill btn-wd " href="{% url 'solicitudes:index' %}">Cancelar</a>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/solicitudes/listar.html
{% extends 'base/base.html' %}

{% block title %}
    Solicitudes
{% endblock %}

{% block solicitud %}
    class = "active"
{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Listado</h4>
            <p class="category">Solicitudes Almacenadas</p>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">
                <thead>
                <th>ID</th>
                <th>Representante</th>
                <th>Teléfono</th>
                <th>Correo</th>
                <th>Instituto</th>
                <th>Grado</th>
                <th>Estudiante</th>
                <th>Estado</th>
                <th>Acciones</th>
                </thead>
                <tbody>
                {% if solicitudes %}
                {% for solicitud in solicitudes %}
                <tr>
                    <td>{{ solicitud.id}}</td>
                    <td>{{ solicitud.representante }}</td>
                    <td>{{ solicitud.telefono }}</td>
                    <td>{{ solicitud.correo }}</td>
                    <td>{{ solicitud.instituto.nombre }}</td>
                    <td>{{ solicitud.grado.descripcion }}</td>
                    <td>{{ solicitud.estudiante}}</td>
                    <td>{% if solicitud.estado == 'P' %}
                            Pendiente
                        {% elif solicitud.estado == 'PR' %}
                            Presupuestado
                        {% elif solicitud.estado == 'PA' %}
                            Pagado
                        {% else %}
                            Enviado
                        {% endif %}
                    </td>
                    <td>
                       {% if solicitud.estado == 'P' %}
                            <a href="{% url 'solicitudes:cotizacion' solicitud.id %}" style=" font-size: 22px; margin-left: 25%" title="Enviar Presupuesto" class="ti-email" id ="icon"></a>
                        {% elif solicitud.estado == 'PR' %}
                            <a href="{% url 'solicitudes:eliminar' solicitud.id %}" style=" font-size: 22px; margin-left: 25%" title="Eliminar" class="ti-trash" id ="icon"></a>
                        {% elif solicitud.estado == 'PA' %}
                            <a href="{% url 'solicitudes:enviar' solicitud.id %}" style=" font-size: 22px; margin-left: 25%" title="Despachar" class="ti-check-box" id ="icon"></a>
                        {% else %}
                            Enviado
                        {% endif %}

                    </td>
                </tr>
                {% endfor %}
                {% else %}
                    <tr>
						<td colspan='9' align='center'>La consulta no devolvió registros</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
            <ul class = "pager">
                <li>
                    <a href="#">Atras</a>
                </li>
                <li>
                    <a href="#">Siguiente</a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}