apps/listas/urls.py
from django.conf.urls import url
from apps.listas.views import index,listas_view, listas_edit, listas_delete, listas_detalle
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    url(r'^nuevo$',login_required(listas_view) , name='listas_crear'),
    url(r'^editar/(?P<id_lista>\d+)/$', login_required(listas_edit), name='listas_editar'),
    url(r'^eliminar/(?P<id_lista>\d+)/$', login_required(listas_delete), name='listas_eliminar'),
    url(r'^detalle/(?P<id_lista>\d+)/$', login_required(listas_detalle), name='listas_detalle'),
]

lista123/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.solicitudes.views import index_principal
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', index_principal, name='inicio'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,{'template_name':'base/login.html'} ,name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/grados/', include('apps.grados.urls', namespace="grados")),
    url(r'^dashboard/institutos/', include('apps.institutos.urls', namespace="institutos")),
    url(r'^dashboard/listas/', include('apps.listas.urls', namespace="listas")),
    url(r'^dashboard/productos/', include('apps.productos.urls', namespace="productos")),
    url(r'^dashboard/solicitudes/', include('apps.solicitudes.urls', namespace="solicitudes")),
    url(r'^dashboard/sugerencias/', include('apps.sugerencias.urls', namespace="sugerencias")),
    url(r'^dashboard/utilidades/', include('apps.utilidades.urls', namespace="utilidades")),
] #+ static(settings.STATIC_ROOT, document_root = settings.STATIC_ROOT)

apps/listas/models.py
from django.db import models
from apps.institutos.models import Instituto
from apps.grados.models import Grado
from apps.productos.models import Producto

# Create your models here.
class Lista(models.Model):
    instituto = models.ForeignKey(Instituto, null=False, blank=False, on_delete=models.CASCADE)
    grado = models.ForeignKey(Grado, null =False, blank=False, on_delete=models.CASCADE)
    producto = models.ManyToManyField(Producto)

apps/institutos/forms.py
from django import forms
from apps.institutos.models import Instituto,Departamento
from smart_selects.form_fields import ModelChoiceField

class InstitutosForm(forms.ModelForm):
    '''nombre = forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Nombre',})
    nombre.render('nombre',None)
    carrera = forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Carrera',})
    calle = forms.Textarea(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Direccion',})
    municipio = forms.Select(attrs={'class': 'form-control border-input'})
    departamento = forms.Select(attrs={'class': 'form-control border-input'})
    categoria = forms.Select(attrs={'class': 'form-control border-input'})'''

    class Meta:
        model = Instituto

        fields =[
            'nombre',
            'carrera',
            'calle',
            'departamento',
            'categoria',
        ]

        labels = {
            'nombre': 'Nombre',
            'carrera': 'Carrera',
            'calle': 'Calle',
            'departamento': 'Departamento',
            'categoria' : 'Categoria',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Nombre',}),
            'carrera': forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Carrera',}),
            'calle': forms.Textarea(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Direccion',}),
            'departamento': forms.Select(attrs={'class':'form-control border-input'}),
            'categoria': forms.Select(attrs={'class':'form-control border-input'}),
        }

apps/listas/forms.py
from django import forms
from apps.listas.models import Lista

class ListasForm (forms.ModelForm):

    class Meta:
        model = Lista

        fields = [
            'instituto',
            'grado',
            'producto',
        ]

        labels = {
            'instituto': 'Instituto',
            'grado': 'Grado',
            'producto' : 'Producto',
        }

        widgets = {
            'instituto' : forms.HiddenInput(attrs={'class':'form-control border-input'}),
            'grado' : forms.Select(attrs={'class':'form-control border-input'}),
            'producto' : forms.SelectMultiple(attrs={'class':'form-control border-input'}),
        }

apps/listas/views.py
from django.shortcuts import render, redirect
from apps.listas.models import Lista
from apps.institutos.models import Instituto
from apps.utilidades.models import Departamento, Municipio
from apps.productos.models import Producto
from apps.listas.forms import ListasForm

# Create your views here.
def index(request):
    #lista = Lista.objects.all().order_by('id')
    lista = Lista.objects.select_related("instituto").select_related("grado").order_by('instituto__nombre')
    contexto = {'listas':lista}
    return render(request,'listas/listar.html', contexto)

def listas_view (request):
    if request.method == 'POST':
        form = ListasForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('listas:index')
    else:
        form = ListasForm()
    return render(request, 'listas/agregar.html', {'form': form})

def listas_edit (request, id_lista):
    lista = Lista.objects.get(id = id_lista)
    departamentos = Departamento.objects.all()
    municipios = Municipio.objects.filter(departamento=lista.instituto.departamento.pk)
    institutos = Instituto.objects.filter(municipio=lista.instituto.municipio.pk)
    if request.method == 'GET':
        form = ListasForm(instance=lista)
    else:
        form = ListasForm(request.POST, instance=lista)
        if form.is_valid():
            form.save()
        return redirect('listas:index')
    return render(request, 'listas/editar.html', {'form':form, 'departamentos':departamentos, 'departamento': lista.instituto.departamento_id, 'municipios': municipios, 'municipio': lista.instituto.municipio_id, 'institutos': institutos, 'instituto': lista.instituto.pk})

def listas_delete (request, id_lista):
    lista = Lista.objects.get(id = id_lista)
    if request.method == 'POST':
        lista.delete()
        return redirect('listas:index')
    return render(request, 'listas/eliminar.html', {'lista':lista})

def listas_detalle(request, id_lista):
    producto = Producto.objects.filter(lista=id_lista)
    contexto = {'productos': producto}
    return render(request,'listas/detalle.html', contexto)

templates/listas/agregar.html
{% extends 'listas/listar.html' %}
{% load staticfiles %}

{% block css %}

{% endblock %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">{% block titleform %}Nueva Lista {% endblock %}</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    {{ form.instituto }}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label >Departamento</label>
                                 <select class="form-control border-input " id="id_departamento" name="id_departamento" required>
                                    {% block select_departamento %}
                                     <option value="" >---------</option>
                                    {% endblock %}
                                 </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label >Municipio</label>
                                 <select class="form-control border-input " id="id_municipio" name="id_municipio" required>
                                    {% block select_municipio %}
                                     <option value="" >---------</option>
                                    {% endblock %}
                                 </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Instituto</label>
                                <select class="form-control border-input " id="s_instituto" name="s_instituto" required>
                                    {% block select_instituto %}
                                     <option value="" >---------</option>
                                    {% endblock %}
                                 </select>
                            </div>
                        </div>
                         <div class="col-md-6">
                            <div class="form-group">
                                <label >Grado</label>
                                {{ form.grado }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                                <label >Productos</label>
                                {{ form.producto}}
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Guardar</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).on('ready',function(){
        buscarDepartamento();
    });

    function buscarDepartamento(){
    $.ajax({
        dataType : 'json',
        method : 'POST',
        url : '/dashboard/institutos/buscar_departamento',
        data : {
            csrfmiddlewaretoken: '{{ csrf_token  }}'
        },
        success : function(data) {
            console.log(data);
            if(!jQuery.isEmptyObject(data)){
                 var opciones = '<option value= "" data-tokens="">---------</option>';
                $.each(data,function(indice, valor){
                    opciones+='<option value="'+valor.pk+'" data-tokens="'+valor.fields.descripcion+'">'+valor.fields.descripcion+'</option>';
                });
            }else{
                var opciones = '<option value= "" data-tokens="">---------</option>';
            }
            $("#id_departamento").html(opciones);

            $('.selectpicker').selectpicker('refresh');
        }
    });
    }

    $("#id_departamento").change(function (){
        var id_departamento = $(this).val();
        buscarMunicipio(id_departamento);
        var opciones = '<option value= "" data-tokens="">---------</option>';
        $("#s_instituto").html(opciones);
        $('.selectpicker').selectpicker('refresh');
    });

    function buscarMunicipio(id_departamento){
    $.ajax({
        dataType : 'json',
        method : 'POST',
        url : '/dashboard/institutos/buscar_municipio',
        data : {
            departamento: id_departamento,csrfmiddlewaretoken: '{{ csrf_token  }}'
        },
        success : function(data) {
            console.log(data);
            if(!jQuery.isEmptyObject(data)){
                var opciones = '<option value= "" data-tokens="">---------</option>';
                 $.each(data,function(indice, valor){
                    opciones+='<option value="'+valor.pk+'" data-tokens="'+valor.fields.descripcion+'">'+valor.fields.descripcion+'</option>';
                 });
            }else{
                var opciones = '<option value= "" data-tokens="">---------</option>';
            }

            $("#id_municipio").html(opciones);

            $('.selectpicker').selectpicker('refresh');
        }
    });
    }

    $("#id_municipio").change(function (){
        var id_municipio = $(this).val();
        buscarInstituto(id_municipio);
    });

    function buscarInstituto(id_municipio){
    $.ajax({
        dataType : 'json',
        method : 'POST',
        url : '/dashboard/institutos/buscar_instituto',
        data : {
            municipio: id_municipio,csrfmiddlewaretoken: '{{ csrf_token  }}'
        },
        success : function(data) {
            console.log(data);
            if(!jQuery.isEmptyObject(data)){
                var opciones = '<option value= "" data-tokens="">---------</option>';
                 $.each(data,function(indice, valor){
                     opciones+='<option value="'+valor.pk+'" data-tokens="'+valor.fields.nombre+'">'+valor.fields.nombre+'</option>';
                 });
            }else{
                 var opciones = '<option value= "" data-tokens="">---------</option>';
            }

            $("#s_instituto").html(opciones);

            $('.selectpicker').selectpicker('refresh');
        }
    });
    }

    $("#s_instituto").change(function (){
        var id_instituto = $(this).val();
        document.getElementById("id_instituto").value = id_instituto;
    });

</script>
{% endblock %}

templates/listas/detalle.html
{% extends 'listas/listar.html' %}

{% block title %}
    Listas Escolares
{% endblock %}

{% block escolar %}
    class = "active"
{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Detalle</h4>
            <p class="category">Productos Asociados</p>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">
                <thead>
                <th>ID</th>
                <th>Descripción</th>
                </thead>
                <tbody>
                {% if productos %}
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.id}}</td>
                    <td>{{ producto.nombre }}</td>
                </tr>
                {% endfor %}
                {% else %}
                    <tr>
						<td colspan='2' align='center'>La consulta no devolvió registros</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/listas/editar.html
{% extends 'listas/agregar.html' %}

{% block titleform %}
    Editar Lista
{% endblock %}

{% block select_departamento %}
    {% if departamentos %}
        <option value="" >---------</option>
        {% for dep in departamentos %}
        <option value="{{ dep.pk }}"
            {% if departamento == dep.pk %}
                selected="selected">
            {% else %}
                >
            {% endif %}
        {{ dep.descripcion }}
        </option>
        {% endfor %}
    {% else %}
        <option value="" selected="selected">---------</option>
    {% endif %}
{% endblock %}

{% block select_municipio %}
    {% if municipios %}
        <option value="" >---------</option>
        {% for mun in municipios %}
        <option value="{{ mun.pk }}"
            {% if municipio == mun.pk %}
                selected="selected">
            {% else %}
                >
            {% endif %}
        {{ mun.descripcion }}
        </option>
        {% endfor %}
    {% else %}
        <option value="" selected="selected">---------</option>
    {% endif %}
{% endblock %}

{% block select_instituto %}
    {% if institutos %}
        <option value="" >---------</option>
        {% for ins in institutos %}
        <option value="{{ ins.pk }}"
            {% if instituto == ins.pk %}
                selected="selected">
            {% else %}
                >
            {% endif %}
        {{ ins.nombre }}
        </option>
        {% endfor %}
    {% else %}
        <option value="" selected="selected">---------</option>
    {% endif %}
{% endblock %}

{% block scripts %}
<script type="text/javascript">

    $("#id_departamento").change(function (){
        var id_departamento = $(this).val();
        buscarMunicipio(id_departamento);
        var opciones = '<option value= "" data-tokens="">---------</option>';
        $("#s_instituto").html(opciones);
        $('.selectpicker').selectpicker('refresh');
    });

    function buscarMunicipio(id_departamento){
    $.ajax({
        dataType : 'json',
        method : 'POST',
        url : '/dashboard/institutos/buscar_municipio',
        data : {
            departamento: id_departamento,csrfmiddlewaretoken: '{{ csrf_token  }}'
        },
        success : function(data) {
            console.log(data);
            if(!jQuery.isEmptyObject(data)){
                var opciones = '<option value= "" data-tokens="">---------</option>';
                 $.each(data,function(indice, valor){
                    opciones+='<option value="'+valor.pk+'" data-tokens="'+valor.fields.descripcion+'">'+valor.fields.descripcion+'</option>';
                 });
            }else{
                var opciones = '<option value= "" data-tokens="">---------</option>';
            }

            $("#id_municipio").html(opciones);

            $('.selectpicker').selectpicker('refresh');
        }
    });
    }

    $("#id_municipio").change(function (){
        var id_municipio = $(this).val();
        buscarInstituto(id_municipio);
    });

    function buscarInstituto(id_municipio){
    $.ajax({
        dataType : 'json',
        method : 'POST',
        url : '/dashboard/institutos/buscar_instituto',
        data : {
            municipio: id_municipio,csrfmiddlewaretoken: '{{ csrf_token  }}'
        },
        success : function(data) {
            console.log(data);
            if(!jQuery.isEmptyObject(data)){
                var opciones = '<option value= "" data-tokens="">---------</option>';
                 $.each(data,function(indice, valor){
                     opciones+='<option value="'+valor.pk+'" data-tokens="'+valor.fields.nombre+'">'+valor.fields.nombre+'</option>';
                 });
            }else{
                 var opciones = '<option value= "" data-tokens="">---------</option>';
            }

            $("#s_instituto").html(opciones);

            $('.selectpicker').selectpicker('refresh');
        }
    });
    }

    $("#s_instituto").change(function (){
        var id_instituto = $(this).val();
        document.getElementById("id_instituto").value = id_instituto;
    });
</script>
{% endblock %}

templates/listas/eliminar.html
{% extends 'listas/listar.html' %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">¿Desea eliminar la  lista del Instituto {{ lista.instituto }} para el Grado {{ lista.grado }}?</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Si, Eliminar</button>
                        <a class="btn btn-info btn-fill btn-wd " href="{% url 'listas:index' %}">Cancelar</a>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/listas/listar.html
{% extends 'base/base.html' %}

{% block title %}
    Listas Escolares
{% endblock %}

{% block escolar %}
    class = "active"
{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Listado</h4>
            <p class="category">Listas Almacenadas</p>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">
                <thead>
                <th>ID</th>
                <th>Instituto</th>
                <th>Grado</th>
                <th >Acciones <a href="{% url 'listas:listas_crear' %}" style=" font-size: 18px;" title="Nuevo" class="ti-plus" id ="icon"></a></th>
                </thead>
                <tbody>
                {% if listas %}
                {% for lista in listas %}
                <tr>
                    <td>{{ lista.id }}</td>
                    <td>{{ lista.instituto.nombre }}</td>
                    <td>{{ lista.grado.descripcion}}</td>
                    <td>
                        <a href="{% url 'listas:listas_editar' lista.id %}" style=" font-size: 22px; margin-left: 0%" title="Editar" class="ti-pencil" id ="icon"></a>
                        <a href="{% url 'listas:listas_eliminar' lista.id %}" style=" font-size: 22px; margin-left: 5%" title="Eliminar" class="ti-trash" id ="icon"></a>
                        <a href="{% url 'listas:listas_detalle' lista.id %}" style=" font-size: 22px; margin-left: 5%" title="Detalle" class="ti-search" id ="icon"></a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                    <tr>
						<td colspan='4' align='center'>La consulta no devolvió registros</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}