apps/institutos/urls.py
from django.conf.urls import url
from apps.institutos.views import index,institutos_view,institutos_edit,institutos_delete, get_municipio, get_departamentos, get_instituto
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    url(r'^nuevo$', login_required(institutos_view), name='institutos_crear'),
    url(r'^editar/(?P<id_instituto>\d+)/$', login_required(institutos_edit), name='institutos_editar'),
    url(r'^eliminar/(?P<id_instituto>\d+)/$', login_required(institutos_delete), name='institutos_eliminar'),
    url(r'^buscar_departamento$', login_required(get_departamentos), name='buscar_departamento'),
    url(r'^buscar_municipio$', login_required(get_municipio), name='buscar_municipio'),
    url(r'^buscar_instituto$', login_required(get_instituto), name='buscar_instituto'),
]

lista123/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.solicitudes.views import index_principal
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', index_principal, name='inicio'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,{'template_name':'base/login.html'} ,name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/grados/', include('apps.grados.urls', namespace="grados")),
    url(r'^dashboard/institutos/', include('apps.institutos.urls', namespace="institutos")),
    url(r'^dashboard/listas/', include('apps.listas.urls', namespace="listas")),
    url(r'^dashboard/productos/', include('apps.productos.urls', namespace="productos")),
    url(r'^dashboard/solicitudes/', include('apps.solicitudes.urls', namespace="solicitudes")),
    url(r'^dashboard/sugerencias/', include('apps.sugerencias.urls', namespace="sugerencias")),
    url(r'^dashboard/utilidades/', include('apps.utilidades.urls', namespace="utilidades")),
] #+ static(settings.STATIC_ROOT, document_root = settings.STATIC_ROOT)

apps/institutos/models.py
from django.db import models
from apps.utilidades.models import Categoria,Municipio,Departamento

# Create your models here.
class Instituto(models.Model):
    nombre = models.CharField(max_length=50)
    carrera = models.CharField(max_length=50)
    calle = models.CharField(max_length=60)
    departamento = models.ForeignKey(Departamento, null=False, blank=False)
    municipio = models.ForeignKey(Municipio, null=False, blank=False)
    categoria = models.ForeignKey(Categoria, null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.nombre)

apps/institutos/forms.py
from django import forms
from apps.institutos.models import Instituto,Departamento
from smart_selects.form_fields import ModelChoiceField

class InstitutosForm(forms.ModelForm):
    '''nombre = forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Nombre',})
    nombre.render('nombre',None)
    carrera = forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Carrera',})
    calle = forms.Textarea(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Direccion',})
    municipio = forms.Select(attrs={'class': 'form-control border-input'})
    departamento = forms.Select(attrs={'class': 'form-control border-input'})
    categoria = forms.Select(attrs={'class': 'form-control border-input'})'''

    class Meta:
        model = Instituto

        fields =[
            'nombre',
            'carrera',
            'calle',
            'departamento',
            'categoria',
        ]

        labels = {
            'nombre': 'Nombre',
            'carrera': 'Carrera',
            'calle': 'Calle',
            'departamento': 'Departamento',
            'categoria' : 'Categoria',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Nombre',}),
            'carrera': forms.TextInput(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Carrera',}),
            'calle': forms.Textarea(attrs={'class':'form-control border-input', 'type': 'text', 'placeholder': 'Direccion',}),
            'departamento': forms.Select(attrs={'class':'form-control border-input'}),
            'categoria': forms.Select(attrs={'class':'form-control border-input'}),
        }

apps/institutos/views.py
from django.shortcuts import render,redirect
from apps.institutos.forms import InstitutosForm
from apps.institutos.models import Instituto, Municipio, Departamento
from django.http import HttpResponseBadRequest, HttpResponse
from django.core import serializers

# Create your views here.
def index(request):
    instituto = Instituto.objects.all().order_by('id')
    contexto = {'institutos':instituto}
    return render(request,'institutos/listar.html', contexto)

def institutos_view (request):
    if request.method == 'POST':
        form = InstitutosForm(request.POST)
        if form.is_valid():
            instituto = form.save(commit=False)
            instituto.municipio_id = request.POST.get('id_municipio')
            instituto.save()
        return redirect('institutos:index')
    else:
        form = InstitutosForm()
    return render(request, 'institutos/agregar.html', {'form': form})

def institutos_edit (request, id_instituto):
    instituto = Instituto.objects.get(id = id_instituto)
    municipios = Municipio.objects.filter(departamento_id = instituto.departamento)
    if request.method == 'GET':
        form = InstitutosForm(instance=instituto)
    else:
        form = InstitutosForm(request.POST, instance=instituto)
        if form.is_valid():
            instituto = form.save(commit=False)
            instituto.municipio_id = request.POST.get('id_municipio')
            instituto.save()
        return redirect('institutos:index')
    return render(request, 'institutos/editar.html', {'form':form,'municipios': municipios,'municipio':instituto.municipio })

def institutos_delete (request, id_instituto):
    instituto = Instituto.objects.get(id = id_instituto)
    if request.method == 'POST':
        instituto.delete()
        return redirect('institutos:index')
    return render(request, 'institutos/eliminar.html', {'instituto':instituto})

def get_municipio(request):
    """Obtiene una lista de categorias dado un padre"""
    # si no es una peticion ajax, devolvemos error 400
    if not request.is_ajax() or request.method != "POST":
        return HttpResponseBadRequest()

    # definimos el termino de busqueda
    padre = request.POST['departamento']
    hijos = Municipio.objects.filter(departamento_id=padre)

    prod_fields = ('id', 'descripcion', )

    data = serializers.serialize('json', hijos, fields=prod_fields)
    return HttpResponse(data, content_type="application/json")

def get_departamentos(request):
    if not request.is_ajax() or request.method != "POST":
        return HttpResponseBadRequest()

    padre = Departamento.objects.all()

    prod_fields = ('id', 'descripcion',)

    data = serializers.serialize('json',padre,fields= prod_fields)
    return HttpResponse(data, content_type="application/json")

def get_instituto(request):
    if not request.is_ajax() or request.method != "POST":
        return HttpResponseBadRequest()

        # definimos el termino de busqueda
    padre = request.POST['municipio']
    hijos = Instituto.objects.filter(municipio_id=padre)

    prod_fields = ('id', 'nombre',)

    data = serializers.serialize('json', hijos, fields=prod_fields)
    return HttpResponse(data, content_type="application/json")

templates/institutos/agregar.html
{% extends 'institutos/listar.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-chosen.css' %}">
{% endblock %}
{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">{% block titleform %}Nuevo Instituto {% endblock %}</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Nombre</label>
                                {{ form.nombre }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label >Carrera</label>
                                {{ form.carrera }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label >Categoría</label>
                                {{ form.categoria}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Dirección</label>
                                {{ form.calle }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Departamento</label>
                                {{ form.departamento }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label >Municipio</label>
                                 <select class="form-control border-input " id="id_municipio" name="id_municipio" required>
                                    {% block select_municipio %}
                                     <option value="" selected="selected">---------</option>
                                    {% endblock %}
                                 </select>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Guardar</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
     $("#id_departamento").change(function (){
        var id_departamento = $(this).val();

        buscarMunicipio(id_departamento);
    });

    function buscarMunicipio(id_departamento){
    $.ajax({
        dataType : 'json',
        method : 'POST',
        url : '/dashboard/institutos/buscar_municipio',
        data : {
            departamento: id_departamento,csrfmiddlewaretoken: '{{ csrf_token  }}'
        },
        success : function(data) {
            console.log(data);
            var opciones = "";
            $.each(data,function(indice, valor){
                opciones+='<option value="'+valor.pk+'" data-tokens="'+valor.fields.descripcion+'">'+valor.fields.descripcion+'</option>';
            });

            $("#id_municipio").html(opciones);

            $('.selectpicker').selectpicker('refresh');
        }
    });
    }
    </script>

{% endblock %}

templates/institutos/editar.html
{% extends 'institutos/agregar.html' %}

{% block titleform %}
    Editar Instituto
{% endblock %}

{% block select_municipio %}
    {% if municipios %}
        <option value="" >---------</option>
        {% for mun in municipios %}
        <option value="{{ mun.id }}"
            {% if municipio.id == mun.id %}
                selected="selected">
            {% else %}
                >
            {% endif %}
        {{ mun.descripcion }}
        </option>
        {% endfor %}
    {% else %}
        <option value="" selected="selected">---------</option>
    {% endif %}
{% endblock %}

templates/institutos/eliminar.html
{% extends 'institutos/listar.html' %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">¿Desea eliminar el registro de {{ instituto.nombre }}?</h4>
            </div>
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd "> Si, Eliminar</button>
                        <a class="btn btn-info btn-fill btn-wd " href="{% url 'institutos:index' %}">Cancelar</a>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/institutos/listar.html
{% extends 'base/base.html' %}

{% block title %}
    Institutos
{% endblock %}

{% block instituto %}
    class = "active"
{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Listado</h4>
            <p class="category">Institutos Almacenados</p>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-striped">
                <thead>
                <th>ID</th>
                <th>Nombre</th>
                <th>Categoría</th>
                <th>Departamento</th>
                <th>Municipio</th>
                <th >Acciones <a href="{% url 'institutos:institutos_crear' %}" style=" font-size: 18px;" title="Nuevo" class="ti-plus" id ="icon"></a></th>
                </thead>
                <tbody>
                {% if institutos %}
                {% for instituto in institutos %}
                <tr>
                    <td>{{ instituto.id }}</td>
                    <td>{{ instituto.nombre }}</td>
                    <td>{{ instituto.categoria }}</td>
                    <td>{{ instituto.departamento }}</td>
                    <td>{{ instituto.municipio }}</td>
                    <td>
                        <a href="{% url 'institutos:institutos_editar' instituto.id %}" style=" font-size: 22px; margin-left: 2%" title="Editar" class="ti-pencil" id ="icon"></a>
                        <a href="{% url 'institutos:institutos_eliminar' instituto.id %}" style=" font-size: 22px; margin-left: 5%" title="Eliminar" class="ti-trash" id ="icon"></a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                    <tr>
						<td colspan='6' align='center'>La consulta no devolvió registros</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}